server.port: 9000
endpoint: http://0.0.0.0:8090/soap
modules:
  bpay:
    use: true
    service: REMOTE
    url: none
    soap: true
    point: none
    merchantId: none
    signature: none
  yandex:
    use: yes
    service: LOCAL
    url: none
    soap: true
  qiwi:
    use: yes
    service: LOCAL
    url: none
    soap: true
  leader:
    use: yes
    service: LOCAL
    url: none
    soap: true
    point: none
  fias:
    use: yes
    service: LOCAL
    url: none
    soap: true
    format: DBF
  jpos:
    use: yes
    service: BOTH
    url: none
    soap: false
    port: 9123
    bufferSize: 2048
  mstercard:
    use: no
  visa:
    use: no
  print:
    use: no
    service: no
    url: no
  forex:
    use: no
    service: no
    url: no

dao: ORACLE_POOL

oraclePool:
    jdbcUrl: none
    username: user
    password: password
    maxLimit: 50
    initialLimit: 5
    connectionTimeout: 30

postgresql:
    jdbcUrl: none
    username: user
    password: password

postgresql-pool:
    jdbcUrl: none
    username: none
    password: none
    initialLimit: 5
    maxLimit: 30
    connectionTimeout: 30

oracle:
    jdbcUrl: none
    username: username
    password: password

mysql:
    jdbcUrl: none
    username: none
    password: none

mysql-pool:
    jdbcUrl: none
    username: none
    password: none
    initialLimit: 5
    maxLimit: 30
    connectionTimeout: 30

log:
    type: LOCAL
    level: 1
gui: true

tracking:
    use: no
    otrs:
      use: no
    redmine:
      use: no
    jira:
      use: yes
      url: "http://192.168.0.20:8080"
      username: "username"
      password: "password"