modules:
  artosis:
      use: yes
      service: remote
      url: none
      point: none
  idc:
      use: no
      service: local
      url: none
      point: none
  yandex:
      use: yes
      service: local
      url: none
  qiwi:
      use: yes
      service: local
      url: none
  leader:
      use: yes
      service: local
      url: none
      point: none

dao: oracle-pool