modules:
  artosis: no
  idc: no
  yandex:
      use: yes
      service: local
      url: none
  qiwi:
      use: yes
      service: local
      url: none
  leader:
      use: yes
      service: local
      url: none

dao: oracle-pool