endpoint: http://127.0.0.1:8090/soap
modules:
  bpay:
      use: yes
      service: remote
      url: none
      point: none
      merchantId: none
      signature: none
  idc:
      use: no
      service: local
      url: none
      point: none
  yandex:
      use: yes
      service: local
      url: none
  qiwi:
      use: yes
      service: local
      url: none
  leader:
      use: yes
      service: local
      url: none
      point: none

dao: oracle-pool

oracle-pool:
      jdbcUrl: none
      username: user
      password: password
      minLimit: 5
      maxLimit: 50
      initialLimit: 5
      connectionTimeout: 30
      validateConnection: true
