
package net.scnetwork.bus.clients.fias;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DownloadServiceSoap", targetNamespace = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DownloadServiceSoap {


    /**
     * Возвращает информацию о последней версии файлов, доступных для скачивания
     * 
     * @return
     *     returns net.scnetwork.bus.clients.fias.DownloadFileInfo
     */
    @WebMethod(operationName = "GetLastDownloadFileInfo", action = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx/GetLastDownloadFileInfo")
    @WebResult(name = "GetLastDownloadFileInfoResult", targetNamespace = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx")
    @RequestWrapper(localName = "GetLastDownloadFileInfo", targetNamespace = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx", className = "net.scnetwork.bus.clients.fias.GetLastDownloadFileInfo")
    @ResponseWrapper(localName = "GetLastDownloadFileInfoResponse", targetNamespace = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx", className = "net.scnetwork.bus.clients.fias.GetLastDownloadFileInfoResponse")
    public DownloadFileInfo getLastDownloadFileInfo();

    /**
     * Возвращает информацию о всех версиях файлов, доступных для скачивания
     * 
     * @return
     *     returns net.scnetwork.bus.clients.fias.ArrayOfDownloadFileInfo
     */
    @WebMethod(operationName = "GetAllDownloadFileInfo", action = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx/GetAllDownloadFileInfo")
    @WebResult(name = "GetAllDownloadFileInfoResult", targetNamespace = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx")
    @RequestWrapper(localName = "GetAllDownloadFileInfo", targetNamespace = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx", className = "net.scnetwork.bus.clients.fias.GetAllDownloadFileInfo")
    @ResponseWrapper(localName = "GetAllDownloadFileInfoResponse", targetNamespace = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx", className = "net.scnetwork.bus.clients.fias.GetAllDownloadFileInfoResponse")
    public ArrayOfDownloadFileInfo getAllDownloadFileInfo();

}
